# syntax=docker/dockerfile:1

FROM python:3.13-slim-bullseye

WORKDIR /app

# Copy Files
COPY ./requirements.txt ./requirements.txt
COPY ./app ./app
COPY ./run.py ./run.py
COPY ./scripts ./scripts
COPY ./Investment_Data.json ./Investment_Data.json

RUN pip3 install -r requirements.txt --no-cache-dir

EXPOSE 5000

CMD [ "python3", "run.py"]
# CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5000"]
