# syntax=docker/dockerfile:1

FROM python:3.13-slim-bullseye

WORKDIR /app

# Copy Files
COPY ./requirements.txt ./requirements.txt
COPY ./streamlitui ./streamlitui
COPY ./.streamlit ./.streamlit

RUN pip3 install -r requirements.txt

# EXPOSE 8501
EXPOSE 80

CMD [ "streamlit", "run", "streamlitui/app.py", "--server.port=80", "--server.address=0.0.0.0"]
